### ISSUE TITLE
SToken Expired

### ISSUE THREAD

**Issue by kfrancis** [xantari/RecaptchaV2.NET#1]
This seems to not work. The Google control simply displays "SToken Expired". Any ideas?

**Comment by xantari** [comment]
Several possibilities exist:
1. You did not put in your google site and secret keys
2. You put them in, but are using the version 1.0 ones instead of the 2.0 ones
3. You modified the example page in a way that would not load a new recaptcha HTML element on each page load (GUID's must be unique for each load).
4. You put the site and secret keys in only one spot, instead of all 4 spots in the example page

**Comment by xantari** [comment]
Include a fiddler trace of the request / response and I may be able to help you further.
